[package]
name = "core-routing"
version = "0.1.0"
edition = "2021"

[dependencies]
core-crypto = { path = "../core-crypto" }
serde = { version = "1", features = ["derive"] }
serde_bytes = "0.11"
thiserror = "1"
serde_json = "1"
ring = "0.17"
